name: Python Tests

on:
  push:
    branches:
      - main  # Cambia esto si deseas que se ejecute en otra rama
    paths:
      - '**/*.py'  # Solo ejecuta el workflow si hay cambios en archivos .py

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Cambia a la versión de Python que necesites

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests
        run: |
          pytest
